### ISSUE TITLE
Review of Report

### ISSUE THREAD

**Issue by johnvm15** [Brainhack-Proceedings-2015/Earl_HBM_HCP_Nipype#1]
The goals of this Brainhack project were to implement the HCP pipeline in Nipype. The project began with three goals: 1) train the would-be Nipype developers on the Nipype python standards; 2) implement the HCP scripts into Nipype interfaces; and 3) secondary goal was to make these sub-level scripts more flexible. Overall this is a very interesting project that would be useful to have available to the neuroimaging community.

Comments:
1. It would be helpful to know how much progress was made on the non-training goals.
2. Can you talk about whether work on this project has continued after Brainhack? If so it might be helpful to provide some info on how others can join this effort.
3. The following wording seems a bit over stated/non-scientific: "on a vastly beneficial project to all of our work"

**Comment by ericearl** [comment]
Thanks for the feedback!  I tried to address each of your comments in the newest revision.  Here are some excerpts:
1. (in results) Conceptually these goals sounded rasonable enough to do all HCP scripts at once during the hackathon, but the learning and additional setup time was not accounted for, so the scope of the project was too big for two days of on and off coding, even among our eleven developers (see Table \ref{collabtable}). Distributing Nipype knowledge from two experts to nine novices over two days was not an easy beginning task, but most of the novices had gained knowledge of Nipype usage by the end of the hackathon. Some work began during the hackathon converting HCP scripts into Nipype pipelines, however not much progress was made due to the unanticipated large scope of work. The second day, an epiphany came about that the original goal, as stated, would have only involved making five top-level wrappers for the five HCP top-level scripts. This also slowed some progress. The secondary goal of generalizing the HCP scripts was discussed, but not thoroughly explored or documented. There has only been some progress in generalization I am aware of in the Damien Fair, PA-C, PhD, Neuroimaging Lab at OHSU. This turnout of developers during an open hackathon is encouraging and demonstrates the importance of trying to fuse these two systems (Nipype and the HCP scripts) to work together. Work on the repository halted after the hackathon, but the team is still available.
2. (in conclusions) Future work will continue trying to achieve the original goals as stated, but may need an organizer to hold the team accountable to deadlines. To get involved with this project, please contact Eric Earl, earl@ohsu.edu.
3. You are totally right.  I was uncertain of how to conclude the conclusions at first.  I removed that excerpt and think the conclusion looks better now.  What do you think?

**Comment by johnvm15** [comment]
Hi Eric, 
I think the additions and changes you made definitely improved the report. 
Good luck with this project!
John

**Comment by ericearl** [comment]
Thanks!  I'm closing this issue then.
